services:
  - type: web
    name: liao-wang-portfolio
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_PASSWORD
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: / 